- name: Create GitHub Actions runner directory
  file:
    path: ~/actions-runner
    state: directory

- name: Download self-hosted runner package
  get_url:
    url: "https://github.com/actions/runner/releases/download/v2.316.0/actions-runner-linux-x64-2.316.0.tar.gz"
    dest: "~/actions-runner/actions-runner-linux-x64-2.316.0.tar.gz"

- name: Extract runner package
  shell: "tar xzf ~/actions-runner/actions-runner-linux-x64-2.316.0.tar.gz -C ~/actions-runner/"

- name: Configure self-hosted runner
  shell: "~/actions-runner/config.sh remove --token {{ TOKEN }} && ~/actions-runner/config.sh --url https://github.com/AzizSouissi/aws-infra-ci-cd --token {{ TOKEN }} --unattended"

- name: Launch self-hosted runner process
  shell: "nohup /home/ubuntu/actions-runner/run.sh > /home/ubuntu/actions-runner/log.out 2>&1 &"
  args:
    chdir: /home/ubuntu/actions-runner
  async: 1
  poll: 0
