name: Build application image, push to GitHub registry, and deploy to server

on:
  push:
    branches: [ main ]
    paths:
      - docker/app/*
      - docker/Dockerfile
      - .github/workflows/deploy.yml
      - trigger

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_REGISTRY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        tags: ghcr.io/${{ github.repository_owner }}/app-image:latest
        push: true           

  deploy-application:
    needs: build-image
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY }}

      - name: Adjust permissions for Docker socket
        run: sudo chmod 666 /var/run/docker.sock

      - name: Pull Docker image from GitHub Container Registry
        run: docker pull ghcr.io/${{ github.repository_owner }}/app-image:latest

      - name: Remove old running containers (if any)
        run: docker rm -f app-container

      - name: Run the application container
        run: docker run -d -p 8080:8080 --name app-container ghcr.io/${{ github.repository_owner }}/app-image:latest
